import Layout from '@/components/Layout'
import Head from 'next/head'
import Image from 'next/image'
import profile from '../../public/images/profile/maicoldev.png'
import AnimationText from '@/components/AnimationText'
import Link from 'next/link'
import { LinkArrow } from '@/components/Icons'
import HireMe from '@/components/HireMe'
import logo from '../../public/images/logo_maicoldev.png'

export default function Home() {
  return (
    <>
      <Head>
        <title>MaicolDev | Michael Rodriguez</title>
        <meta name="description" content="Generated by create next app" />
        
      </Head>
      <main className='flex items-center text-dark w-full min-h-screen dark:text-light'>
        <Layout className='pt-0'>
          <div className='flex items-center justify-between w-full'>
          <div className='w-1/2'>
              <Image src={profile} alt='MaicolDev' className='w-full h-auto' 
              priority
              sizes='(max-width: 768px) 100vw,(max-width: 1200px) 50vw 33vw'
              />
            </div >
            <div className='w-1/2 flex flex-col items-center self-center' >
              <AnimationText className='!text-6xl !text-left' text="Develop imagination with code and make it reality."/>
              <p className='my-4 text-base font-medium'>
                As a skilled full-stack developer, I am dedicated to 
                turning ideas into innovative web applications. 
                Explore my latest projects and articles, showcasing my expertise in React.js and web development.
              </p>
              <div className='flex items-center self-start'>
                <Link className='flex items-center bg-dark text-light 
                p-2.5 px-6 rounded-lg text-lg font-semibold
                hover:bg-light hover:text-dark 
                border-2 border-solid border-transparent hover:border-dark
                dark:bg-light dark:text-dark 
                hover:dark:bg-dark hover:dark:text-light hover:dark:border-light
                ' 
                href="/dummy.pdf"
                download={true} 
                target={"_blank"}>
                  Resume
                  <LinkArrow className={"w-6 ml-1"}/>
                </Link>
                <Link
                className='ml-4 px-6 text-lg font-medium capitalize text-dark
                underline dark:text-light'
                href="mailto:michaelrogger.contacto@gmail.com?Subject=Aquí%20el%20asunto%20del%20mail" target={"_blank"}>
                  Contact
                </Link>
              </div>
            </div>

            
          </div>
        </Layout>

        <HireMe/>
        
        <div className='absolute right-8 bottom-8 inline-block w-48'>
          <Image src={logo} alt='maicoldev' className='w-full h-auto'/>
        </div>
      </main>
    </>
  )
}
