import Layout from '@/components/Layout'
import Head from 'next/head'
import Image from 'next/image'
import profile from '../../public/images/profile/maicoldev.png'
import AnimationText from '@/components/AnimationText'
import Link from 'next/link'
import { LinkArrow } from '@/components/Icons'
import HireMe from '@/components/HireMe'
import logo from '../../public/images/logo_maicoldev.png'
import TransitionEffect from '@/components/utils/TransitionEffect'

export default function Home() {
  return (
    <>
      <Head>
        <title>MaicolDev | Michael Rodriguez</title>
        <meta name="description" content="Generated by create next app" />
        
      </Head>
      <TransitionEffect/>
      <main className='flex items-center text-dark w-full min-h-screen dark:text-light'>
        <Layout className='pt-0 md:pt-16 sm:pt-8'>
          <div className='flex items-center justify-between w-full lg:flex-col'>
          <div className='w-1/2 md:w-full'>
              <Image src={profile} alt='MaicolDev' className='w-full h-auto 
              lg:hidden md:inline-block md:w-full' 
              priority
              sizes='(max-width: 768px) 100vw,(max-width: 1200px) 50vw 33vw'
              />
            </div>
            <div className='w-1/2 flex flex-col items-center self-center
            lg:w-full lg:text-center' >
              <AnimationText 
              className='!text-6xl !text-left
              xl:!text-5xl lg:!text-center lg:!text-6xl md:!text-5xl sm:!text-3xl' 
              text="Develop imagination with code and make it reality."
              //text="Turn vision into reality with code and design."
              />
              <p className='my-4 text-base font-medium
              md:text-sm sm:text-xs'>
                As a skilled full-stack developer, I am dedicated to 
                turning ideas into innovative web applications. 
                Explore my latest projects and articles, showcasing my expertise in React.js and web development.
              </p>
              <div className='flex items-center self-start lg:self-center'>
                <Link className='flex items-center bg-dark text-light 
                p-2.5 px-6 rounded-lg text-lg font-semibold
                hover:bg-light hover:text-dark 
                border-2 border-solid border-transparent hover:border-dark
                dark:bg-light dark:text-dark 
                hover:dark:bg-dark hover:dark:text-light hover:dark:border-light
                md:p-2 md:px-4 md:text-base' 
                href="/dummy.pdf"
                download={true} 
                target={"_blank"}>
                  Resume
                  <LinkArrow className={"w-6 ml-1"}/>
                </Link>
                <Link
                className='ml-4 px-6 text-lg font-medium capitalize text-dark
                underline dark:text-light md:text-base'
                href="mailto:michaelrogger.contacto@gmail.com?Subject=Aquí%20el%20asunto%20del%20mail" target={"_blank"}>
                  Contact
                </Link>
              </div>
            </div>

            
          </div>
        </Layout>

        <HireMe/>
        
        <div className='absolute right-8 bottom-8 inline-block w-40
        md:hidden'>
          <Image src={logo} alt='maicoldev' className='w-full h-auto'/>
        </div>
      </main>
    </>
  )
}
